# Put your code here
# Step1: this is a python code (code.py), pull python image
# Step2: copy ALL the file into the image
# Step3: install the requirements from file
# Step4: Run the command "python" "code.py"
