apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: myapp
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 80
  type: LoadBalancer # service port type is LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    group: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1 # scale up the pods to 1
  template: 
    metadata: 
      labels: 
        app: myapp
    spec:
      containers:
        - name: myapp
          image: twming/myapp-update

# (Terminal 1)
# kubectl apply -f deployment.yaml
# minikube service myservice

# (Terminal 2)
# kubectl set image deployment myapp myapp=twming/myapp-update:1
# kubectl rollout status deployment myapp
# kubectl rollout undo deployment myapp
# kubectl rollout history deployment myapp --revision=1
