FROM ubuntu

RUN apt-get update 
RUN apt-get install -y python3
CMD echo "Python3 package installed!"

# This is comment, run this in command line
# docker build -t mybuild1 .
# docker images
# docker run --name myapp1 mybuild1
