FROM ubuntu

RUN apt-get update 
RUN apt-get install -y python3
CMD ["python3"]

# This is comment, run this in command line
# docker build -t mybuild2 .
# docker images
# docker run --name myapp2 -it mybuild2