apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: myapp
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    group: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template: 
    metadata: 
      labels: 
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: twming/myapp_fail

# deployment with pod and service
# kubectl apply -f deployment.yaml
# minikube service myservice