apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: twming/kub-demo-user:latest
          env:
            - name: AUTH_ADDRESS
              #value: "10.109.233.18"
              # service name . namespace
              value: "auth-service.default"