apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: myapp
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 80
  type: LoadBalancer # service port type is LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    group: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1 # scale up the pods to 1
  template: 
    metadata: 
      labels: 
        app: myapp
    spec:
      containers:
        - name: myapp
          image: twming/myapp-update

# kubectl apply -f deployment.yaml
# kubectl scale deployment myapp --replicas=3
# kubectl scale deployment myapp --replicas=1
# kubectl delete -f deployment.yaml
