FROM mysql:5.7

ENV MYSQL_ROOT_PASSWORD="somewordpress"
ENV MYSQL_DATABASE="wordpress"
ENV MYSQL_USER="wordpress"
ENV MYSQL_PASSWORD="wordpress"

# docker build -t mysql_build .
# docker run --name mysql_app --rm --network mynetwork mysql_build