apiVersion: batch/v1
kind: CronJob
metadata:
  name: myfruitchoice
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: myfruitchoice
            image: twming/cronjob
            command:
            - /bin/bash
            - -c
            - /pgm/choose_fruit.sh
          restartPolicy: OnFailure
