apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    group: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template: 
    metadata: 
      labels: 
        app: myapp
    spec:
      containers:
        - name: myapp
          image: twming/myapp_fail

# kubectl apply -f pod.yaml
