apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      labels:
        app: tasks
    spec:
      containers:
        - name: tasks
          image: twming/kub-demo-task:latest
          env:
            - name: AUTH_ADDRESS
              #value: "10.109.233.18"
              # service name . namespace
              value: "auth-service.default"
            - name: TASKS_FOLDER
              value: tasks