apiVersion: v1
kind: Pod
metadata:
  name: myapp-fail
  labels: 
    app: myapp-fail
spec:
  containers:
  - name: myapp-fail
    image: twming/myapp_fail
    ports:
    - containerPort: 8080

# (Terminal 1)
# kubectl apply -f pod.yaml
# kubectl expose pod myapp-fail --port=8080
# minikube service myapp-fail
