apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - name: testpod
    image: alpine:3.5
    command: ["ping", "8.8.8.8"]

# kubectl apply -f pod.yaml
# kubectl logs pod/demo
# kubectl delete -f pod.yaml

# change the ip to 127.0.0.1, save the pod.yaml
# kubectl apply -f pod.yaml
# kubectl logs pod/demo