apiVersion: v1
kind: Pod
metadata:
  name: myapp-fail
  labels: 
    app: myapp-fail
spec:
  containers:
  - name: myapp-fail
    image: twming/myapp_fail
    ports:
    - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: myapp-fail
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 8080
  type: NodePort


# (Terminal 1)
# kubectl apply -f pod.yaml
# minikube service myservice
